from pydantic import BaseModel
from datetime import datetime
from typing import Optional

# Schema for storing NPC memory interactions
class NPCMemoryCreate(BaseModel):
    player_id: int
    npc_id: int
    dialogue: str

# Schema for returning NPC memory data
class NPCMemoryResponse(NPCMemoryCreate):
    id: int
    player_id: int
    npc_id: int
    dialogue: str
    sentiment: str  # Analyzed from player dialogue
    npc_reply: Optional[str] = None  # Generated by Deepseek
    npc_sentiment: Optional[str] = None  # Analyzed from NPC reply
    timestamp: datetime

    class Config:
        from_attributes = True

class NPCMemoryUpdate(BaseModel):
    dialogue: str

npc_reply: Optional[str]
npc_sentiment: Optional[str]